### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by toyotabedzrock** [ltguillaume/droidshows#4]
On Android 6 version 6 of the app crashes before the interface even opens.

**Comment by ltguillaume** [comment]
Hi!

Could you send me a logcat? If you're not familiar with this, you can
search the xda forums (or just with google) for a tutorial on how to export
a logcat.

Thanks in advance!

**Comment by toyotabedzrock** [comment]
Here is the relevant logcat lines. I tried attaching it but github complains.

[ 10-14 13:32:24.861   780:  791 I/ActivityManager ]

START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=nl.asymmetrics.droidshows/.DroidShows bnds=[276,276][540,573](has extras)} from uid 10014 on display 0

[ 10-14 13:32:24.899   780: 3277 I/ActivityManager ]

Start proc 579:nl.asymmetrics.droidshows/u0a343 for activity nl.asymmetrics.droidshows/.DroidShows

[ 10-14 13:32:24.962   579:  579 W/System   ]

ClassLoader referenced unknown path: /data/app/nl.asymmetrics.droidshows-1/lib/arm

--------- beginning of crash

[ 10-14 13:32:25.094   579:  627 E/AndroidRuntime ]

FATAL EXCEPTION: AsyncTask #1

Process: nl.asymmetrics.droidshows, PID: 579

java.lang.RuntimeException: An error occurred while executing doInBackground()

```
at android.os.AsyncTask$3.done(AsyncTask.java:309)

at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)

at java.util.concurrent.FutureTask.setException(FutureTask.java:223)

at java.util.concurrent.FutureTask.run(FutureTask.java:242)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

at java.lang.Thread.run(Thread.java:818)
```

Caused by: java.util.ConcurrentModificationException

```
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)

at nl.asymmetrics.droidshows.DroidShows$AsyncInfo.doInBackground(DroidShows.java:1014)

at nl.asymmetrics.droidshows.DroidShows$AsyncInfo.doInBackground(DroidShows.java:1009)

at android.os.AsyncTask$2.call(AsyncTask.java:295)

at java.util.concurrent.FutureTask.run(FutureTask.java:237)

... 3 more
```

[ 10-14 13:32:25.105   780: 3276 W/ActivityManager ]

  Force finishing activity nl.asymmetrics.droidshows/.DroidShows

[ 10-14 13:32:25.411   780: 3276 I/WindowManager ]

Screenshot max retries 4 of Token{9070ee5 ActivityRecord{69bddc u0 nl.asymmetrics.droidshows/.DroidShows t122 f}} appWin=Window{4575be0 u0 nl.asymmetrics.droidshows/nl.asymmetrics.droidshows.DroidShows} drawState=3

[ 10-14 13:32:27.244   780: 3285 I/ActivityManager ]

Process nl.asymmetrics.droidshows (pid 579) has died

**Comment by ltguillaume** [comment]
Ok that's odd... And you're saying v5.9 DOES work on Marshmallow?

**Comment by ltguillaume** [comment]
Can you try this version first: https://github.com/ltGuillaume/DroidShows/releases/download/6.0/DroidShows_6.0e.apk

If it doesn't work, please try this one and if necessary plz provide another logcat: https://github.com/ltGuillaume/DroidShows/releases/download/6.0/DroidShows_6.1TEST.apk

**Comment by platschi** [comment]
Same here, latest version crashes on start with Android 6

/edit: Tested with 6.1TEST, it's working again!

**Comment by ltguillaume** [comment]
Could you please follow the instructions in my last post and report back?
That would be the only way for me to solve this, so your help is much
appreciated :)

**Comment by ltguillaume** [comment]
Did you also try v6.0e? If not, please do, because otherwise I won't know what the actual issue was. PLEASE WAIT UNTIL AFTER MIDNIGHT BEFORE REPORTING BACK (that's when the AsyncTask will run again).

@toyotabedzrock 
@platschi

**Comment by toyotabedzrock** [comment]
@ltGuillaume Sorry lost track of things. The recent update to 6.1 doesn't work for me either. And the two test builds refuse to install after installing 6.1.

**Comment by ltguillaume** [comment]
Hey, thanks for checking. It can't be the exact same error, so could
you please try to make another logcat dump?

As for not being able to install an earlier version, that's probably due to
the fact that you use an F-Droid build?

**Comment by platschi** [comment]
Tested with both versions (6.0e and 6.1TEST), both seem to work. 

Uninstalled the two apks now and installed DroidShows anew from F-Droid (new 6.1 version as of 26/10), all working smoothly. Thanks a lot for your work!

**Comment by ltguillaume** [comment]
Ok, thanks for testing! This is all quite strange now @toyotabedzrock hopefully I can help you out soon if you send me another logcat dump. Cheers!

**Comment by uatach** [comment]
i've upgraded on f-droid from 6.2 to 6.3 and the app stopped working.

12-12 18:09:11.969   816  1199 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=nl.asymmetrics.droidshows cmp=nl.asymmetrics.droidshows/.DroidShows} from uid 10083 on display 0
12-12 18:09:12.101   816  1754 I ActivityManager: Start proc 27754:nl.asymmetrics.droidshows/u0a60 for activity nl.asymmetrics.droidshows/.DroidShows
12-12 18:09:12.225 27754 27754 W System  : ClassLoader referenced unknown path: /data/app/nl.asymmetrics.droidshows-2/lib/arm
12-12 18:09:12.255   816   826 I art     : Background partial concurrent mark sweep GC freed 78358(6MB) AllocSpace objects, 37(956KB) LOS objects, 33% free, 18MB/28MB, paused 2.584ms total 276.315ms
12-12 18:09:12.401  1533  1533 I Keyboard.Facilitator: onFinishInput()
12-12 18:09:12.456 27754 27792 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
12-12 18:09:12.456 27754 27792 E AndroidRuntime: Process: nl.asymmetrics.droidshows, PID: 27754
12-12 18:09:12.456 27754 27792 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    at android.os.AsyncTask$3.done(AsyncTask.java:309)
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    at java.lang.Thread.run(Thread.java:818)
12-12 18:09:12.456 27754 27792 E AndroidRuntime: Caused by: java.util.ConcurrentModificationException
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    at nl.asymmetrics.droidshows.DroidShows$AsyncInfo.doInBackground(DroidShows.java:1015)
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    at nl.asymmetrics.droidshows.DroidShows$AsyncInfo.doInBackground(DroidShows.java:1007)
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-12 18:09:12.456 27754 27792 E AndroidRuntime:    ... 3 more
12-12 18:09:12.461   816  1721 W ActivityManager:   Force finishing activity nl.asymmetrics.droidshows/.DroidShows
12-12 18:09:12.765   816  1721 I WindowManager: Screenshot max retries 4 of Token{a7fc35a ActivityRecord{13d5705 u0 nl.asymmetrics.droidshows/.DroidShows t23608 f}} appWin=Window{31fb514 u0 nl.asymmetrics.droidshows/nl.asymmetrics.droidshows.DroidShows} drawState=3
12-12 18:09:12.766   816  1721 W ActivityManager:   Force finishing activity org.fdroid.fdroid/.AppDetails
12-12 18:09:12.779   816   816 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12802 waiters=0 for 304ms
12-12 18:09:12.818 17880 17880 D LogFetchServiceManager: Received entry added
12-12 18:09:12.880   816 25933 I OpenGLRenderer: Initialized EGL, version 1.4
12-12 18:09:13.253   222   398 I ThermalEngine: Sensor:batt_therm:31700 mC
12-12 18:09:15.068 27754 27792 I Process : Sending signal. PID: 27754 SIG: 9
12-12 18:09:15.083  1533  1533 I Keyboard.Facilitator: onFinishInput()
12-12 18:09:15.112   816  1726 I ActivityManager: Process nl.asymmetrics.droidshows (pid 27754) has died

**Comment by ltguillaume** [comment]
@edsonduarte1990 
- Do you have your shows list ordered by name or by # of unseen episodes?
- Did you do any operation (e.g. from the menu, or a quick swipe to mark next episode as seen) within 1-5 seconds after DroidShows started?
- Can you reproduce the crash now?

**Comment by uatach** [comment]
@ltGuillaume 
- I'm sure it's not by name (I never changed this)
- I did not.
- Every time I start the app.

I think I did not made it clear that I cannot use the app after the update. I start the app and it crashes, I never used the new version and the previous one did not have this problem, and I'm not able do downgrade without uninstalling (both versions are from F-droid).

**Comment by ltguillaume** [comment]
@edsonduarte1990 thanks for the additional info. I've just committed some changes and tagged it for release v6.4. Just wait a day or so until F-Droid picks it up and you'll be able to try it.

**Comment by ltguillaume** [comment]
@edsonduarte1990 it's up. How's v6.4 working out for ya?

**Comment by uatach** [comment]
@ltGuillaume  same problem.

**Comment by ltguillaume** [comment]
@edsonduarte1990 Can't be the exact same problem, as the lines of code referenced in you logcat dump have all been changed). Could you send me another logcat dump? That will give me a lot more info on the problem.

**Comment by ltguillaume** [comment]
@edsonduarte1990 I'm guessing/hoping you have root access to your device, right? If so, could you upload /data/data/nl.asymmetrics.droidshows/databases/DroidShows.db from your phone to [link removed]

Furthermore, you could copy the same file (/data/data/nl.asymmetrics.droidshows/databases/DroidShows.db) to your phone's sd-card and try to uninstall DroidShows, then reinstall the last version you think was still working (you said v6.2) and restore the database via Options. Judging by the code changes between v6.2 and v6.3 I'm not sure this will help you, but it will let me know whether I should look for changes in previous commits, too.

**Comment by uatach** [comment]
sorry for the delay... here's the logcat:

12-19 18:42:30.758  2197  2197 I log     : Launching app://nl.asymmetrics.droidshows/nl.asymmetrics.droidshows.DroidShows
12-19 18:42:30.813  1043  1079 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=nl.asymmetrics.droidshows/.DroidShows} from uid 10063 on display 0
12-19 18:42:30.850  1043  1595 I ActivityManager: Start proc 9359:nl.asymmetrics.droidshows/u0a60 for activity nl.asymmetrics.droidshows/.DroidShows
12-19 18:42:30.943  9359  9359 W System  : ClassLoader referenced unknown path: /data/app/nl.asymmetrics.droidshows-1/lib/arm
12-19 18:42:31.093  9359  9387 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
12-19 18:42:31.093  9359  9387 E AndroidRuntime: Process: nl.asymmetrics.droidshows, PID: 9359
12-19 18:42:31.093  9359  9387 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    at android.os.AsyncTask$3.done(AsyncTask.java:309)
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    at java.lang.Thread.run(Thread.java:818)
12-19 18:42:31.093  9359  9387 E AndroidRuntime: Caused by: java.util.ConcurrentModificationException
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    at nl.asymmetrics.droidshows.DroidShows$AsyncInfo.doInBackground(DroidShows.java:1011)
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    at nl.asymmetrics.droidshows.DroidShows$AsyncInfo.doInBackground(DroidShows.java:1006)
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-19 18:42:31.093  9359  9387 E AndroidRuntime:    ... 3 more
12-19 18:42:31.095  1043  1675 W ActivityManager:   Force finishing activity nl.asymmetrics.droidshows/.DroidShows
12-19 18:42:31.124  1043 26954 D NetlinkSocketObserver: NeighborEvent{elapsedMs=32301512, 192.168.0.1, [84C9B2DC7A0D], RTM_NEWNEIGH, NUD_STALE}
12-19 18:42:31.225  1043  1606 W InputMethodManagerService: Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@3ada7b1 (uid=10060 pid=9359)
12-19 18:42:31.399  1043  1675 I WindowManager: Screenshot max retries 4 of Token{b28bbbe ActivityRecord{82f2279 u0 nl.asymmetrics.droidshows/.DroidShows t24277 f}} appWin=Window{5d34a58 u0 nl.asymmetrics.droidshows/nl.asymmetrics.droidshows.DroidShows} drawState=3
12-19 18:42:31.413  1043  1664 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12802 waiters=2 for 171ms
12-19 18:42:31.445 28622 28622 D LogFetchServiceManager: Received entry added
12-19 18:42:31.464  1043  1374 I OpenGLRenderer: Initialized EGL, version 1.4
12-19 18:42:31.723   234   394 I ThermalEngine: Sensor:batt_therm:32000 mC
12-19 18:42:32.897  9359  9387 I Process : Sending signal. PID: 9359 SIG: 9
12-19 18:42:32.906  1043  1676 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@2b8330f attribute=null, token = android.os.BinderProxy@dc8da6e
12-19 18:42:32.924  1043  2319 I ActivityManager: Process nl.asymmetrics.droidshows (pid 9359) has died

**Comment by uatach** [comment]
removing the app worked...

**Comment by ltguillaume** [comment]
Thanks for the reply! So reinstalling the app worked? With the original database? Or only with a new one?

**Comment by uatach** [comment]
worked with the original database but today it crashed again, did the same thing and it started working again... not sure why, I tested just rebooting the device and it's not the issue, it kept working...

**Comment by ltguillaume** [comment]
Ok, I've read up on the issue some more, and with https://github.com/ltGuillaume/DroidShows/releases/download/6.4/DroidShows_6.5.apk I should circumvent the check in the Iterator that causes the issue (at least according to some sources). I know you're using the F-Droid release and thus will have to remove the app again in order to install this version (due to a different signature), but I hope you'll understand that I can't release an update for everyone as long as I don't know for sure the issue is now resolved. I can't reproduce it myself, so I'd be very grateful if you'd want to test this version for me!

**Comment by uatach** [comment]
it started crashing again today... and i've installed the apk you released, it's working for now.

**Comment by DocSniper** [comment]
The problem isn't gone. Version 6.4 (from F-Droid) is still crashing on Marshmallow.

12-25 11:57:26.683 I/ActivityManager(1082): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=nl.asymmetrics.droidshows/.DroidShows (has extras)} from uid 10009 on display 0
12-25 11:57:26.728 I/ActivityManager(1082): Start proc 28467:nl.asymmetrics.droidshows/u0a391 for activity nl.asymmetrics.droidshows/.DroidShows
12-25 11:57:26.791 W/System  (28467): ClassLoader referenced unknown path: /data/app/nl.asymmetrics.droidshows-2/lib/arm
12-25 11:57:26.880 E/AndroidRuntime(28467): Process: nl.asymmetrics.droidshows, PID: 28467
12-25 11:57:26.880 E/AndroidRuntime(28467):     at nl.asymmetrics.droidshows.DroidShows$AsyncInfo.doInBackground(DroidShows.java:1011)
12-25 11:57:26.880 E/AndroidRuntime(28467):     at nl.asymmetrics.droidshows.DroidShows$AsyncInfo.doInBackground(DroidShows.java:1006)
12-25 11:57:26.897 W/ActivityManager(1082):   Force finishing activity nl.asymmetrics.droidshows/.DroidShows
12-25 11:57:27.201 I/WindowManager(1082): Screenshot max retries 4 of Token{78c2ff2 ActivityRecord{8abb6fd u0 nl.asymmetrics.droidshows/.DroidShows t16506 f}} appWin=Window{7bcfcec u0 nl.asymmetrics.droidshows/nl.asymmetrics.droidshows.DroidShows} drawState=3
12-25 11:57:29.553 I/ActivityManager(1082): Process nl.asymmetrics.droidshows (pid 28467) has died

**Comment by DocSniper** [comment]
Sorry didn't see your 6.5 post before. Installed your 6.5 and this seems to work well. Thanks.

12-25 12:08:37.120 I/ActivityManager(1082): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=nl.asymmetrics.droidshows/.DroidShows (has extras)} from uid 10009 on display 0
12-25 12:08:37.149 I/ActivityManager(1082): Start proc 7032:nl.asymmetrics.droidshows/u0a462 for activity nl.asymmetrics.droidshows/.DroidShows
12-25 12:08:37.205 W/System  (7032): ClassLoader referenced unknown path: /data/app/nl.asymmetrics.droidshows-1/lib/arm
12-25 12:08:37.442 I/ActivityManager(1082): Displayed nl.asymmetrics.droidshows/.DroidShows: +305ms

**Comment by ltguillaume** [comment]
I've committed these changes and fixed 2 other minor issues, hopefully everything will be working now. Thanks for your feedback. v6.5 will automatically turn up in the F-Droid repo soon.
